# Kubernetes example of Volume with empty directory
# - An emptyDir volume allocates the space from the worker node that the pod is running.
# - The data is available through the pod lifecycle and deleted once the pod is removed.
# CLI to create emptydir volume and use it in a Pod
#   kubectl apply -f emptydir.yaml
#   kubectl exec -it mypod-emptydirvol -c main -- curl localhost
apiVersion: v1
kind: Pod
metadata:
  name: mypod-emptydirvol
spec:
  containers:
  - name: main
    image: nginx:alpine
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
  - name: html-generator
    image: luksa/fortune
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
    emptyDir: {}
#   emptyDir:
#     medium: Memory # store data on RAM
