# Kubernetes example for Secret resource
# - Secret resource can be created with this YAML definition
# - This can also be created with data available in separate files like below
#   openssl genrsa -out https.key 2048
#   openssl req -new -x509 -key https.key -out https.cert -days 3650 -subj /CN=www.example.com
#   kubectl create secret generic mysvcaccount --from-file=https.key --from-file=https.cert
# CLI to create this plain secret:
#   kubectl apply -f secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
stringData: # Input only field to specify non sensitive data as plain text
  authUrl: http://example.com/
  username: admin
data: # Base64 encoded sensitive information
  password: YWRtaW4= # echo -n "admin" | base64
  https.cert: MIIDFTCCAf2gAwIBAgIUBRcrqBnFOcccn0GEPkrDzTuP8gAwDQYJKoZIhvcN
  https.key: MIIDFTCCAf2gAwIBAgIUBRcrqBnFOcccn0GEPkrDzTuP8gAwDQYJKoZIhvcN

---

# Kubernetes Pod that uses secret as mounted volume
apiVersion: v1
kind: Pod
metadata:
  name: mysecretpod
spec:
  containers:
  - name: main
    image: nginx
    volumeMounts:
    - name: certvol
      mountPath: /etc/nginx/certs
      readOnly: true
  volumes:
    - name: certvol
      secret:
        secretName: mysecret
