# Kubernetes ConfigMap example
# ConfigMap object is designed to store application configurations that are non sentitive.
# Pods can consume them as environment variables, command line arguments, or volumes.
apiVersion: v1
kind: ConfigMap
metadata:
  name: mycfgmap
data:
  bindHost: "0.0.0.0"
  bindPort: "3456"
  
  # file like keys
  db.config: |
    host=mydb.svc.local
    port=3457
